### ISSUE TITLE
Using of --user "$(id -u):$(id -g)" in docker image not working

### ISSUE THREAD

**Issue by sitems** [TheJacksonLaboratory/Squirls#59]
When I run Squirls like this

`docker run \
  --workdir /opt/squirls \
  --network none \
  --rm \
  --mount type=bind,source="${BIOCACHE}"/squirls,target=/data,readonly \
  --mount "type=bind,source=${PWD},target=/output" \
  --mount "type=bind,source=${PWD}/family_decnorm_filt.vcf.bgz,target=/input/variants.vcf.bgz,readonly" \
urpin/squirls:2.0.0 \
  java -Xmx1000g \
  -jar squirls-cli-2.0.0.jar \
  annotate-vcf \
  --output-format vcf,html \
  --all-transcripts \
  --transcript-source REFSEQ \
  --compress \
  --threads 1 \
  --data-directory /data \
  /input/variants.vcf.bgz \
  /output/family_decnorm_filt_squirls
`

everything works, but the output files have the 'root' owner. So I added 

`--user "$(id -u):$(id -g)" `

as I do in many other bioinformatics docker images, but the command fails:

18:12:55.481 [main] ERROR o.s.boot.SpringApplication - Application run failed
java.lang.IllegalStateException: Logback configuration error detected: 
ERROR in ch.qos.logback.core.FileAppender[FILE] - openFile(squirls.log,false) call failed. java.io.FileNotFoundException: squirls.log (Permission denied)
	at org.springframework.boot.logging.logback.LogbackLoggingSystem.loadConfiguration(LogbackLoggingSystem.java:169)
	at org.springframework.boot.logging.AbstractLoggingSystem.initializeWithConventions(AbstractLoggingSystem.java:80)
	at org.springframework.boot.logging.AbstractLoggingSystem.initialize(AbstractLoggingSystem.java:60)
	at org.springframework.boot.logging.logback.LogbackLoggingSystem.initialize(LogbackLoggingSystem.java:118)
	at org.springframework.boot.context.logging.LoggingApplicationListener.initializeSystem(LoggingApplicationListener.java:313)
	at org.springframework.boot.context.logging.LoggingApplicationListener.initialize(LoggingApplicationListener.java:288)
	at org.springframework.boot.context.logging.LoggingApplicationListener.onApplicationEnvironmentPreparedEvent(LoggingApplicationListener.java:246)
	at org.springframework.boot.context.logging.LoggingApplicationListener.onApplicationEvent(LoggingApplicationListener.java:223)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:172)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:165)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:139)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:127)
	at org.springframework.boot.context.event.EventPublishingRunListener.environmentPrepared(EventPublishingRunListener.java:76)
	at org.springframework.boot.SpringApplicationRunListeners.environmentPrepared(SpringApplicationRunListeners.java:53)
	at org.springframework.boot.SpringApplication.prepareEnvironment(SpringApplication.java:345)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:308)
	at org.springframework.boot.builder.SpringApplicationBuilder.run(SpringApplicationBuilder.java:140)
	at org.monarchinitiative.squirls.cli.cmd.SquirlsCommand.getContext(SquirlsCommand.java:174)
	at org.monarchinitiative.squirls.cli.cmd.annotate_vcf.AnnotateVcfCommand.call(AnnotateVcfCommand.java:255)
	at org.monarchinitiative.squirls.cli.cmd.annotate_vcf.AnnotateVcfCommand.call(AnnotateVcfCommand.java:120)
	at picocli.CommandLine.executeUserObject(CommandLine.java:1933)
	at picocli.CommandLine.access$1200(CommandLine.java:145)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2332)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2326)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2291)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2159)
	at picocli.CommandLine.execute(CommandLine.java:2058)
	at org.monarchinitiative.squirls.cli.Main.main(Main.java:124)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:87)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:51)
	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:52)
18:12:55.490 [main] ERROR o.m.s.c.c.a.AnnotateVcfCommand - Error: 
java.lang.IllegalStateException: Logback configuration error detected: 
ERROR in ch.qos.logback.core.FileAppender[FILE] - openFile(squirls.log,false) call failed. java.io.FileNotFoundException: squirls.log (Permission denied)
	at org.springframework.boot.logging.logback.LogbackLoggingSystem.loadConfiguration(LogbackLoggingSystem.java:169)
	at org.springframework.boot.logging.AbstractLoggingSystem.initializeWithConventions(AbstractLoggingSystem.java:80)
	at org.springframework.boot.logging.AbstractLoggingSystem.initialize(AbstractLoggingSystem.java:60)
	at org.springframework.boot.logging.logback.LogbackLoggingSystem.initialize(LogbackLoggingSystem.java:118)
	at org.springframework.boot.context.logging.LoggingApplicationListener.initializeSystem(LoggingApplicationListener.java:313)
	at org.springframework.boot.context.logging.LoggingApplicationListener.initialize(LoggingApplicationListener.java:288)
	at org.springframework.boot.context.logging.LoggingApplicationListener.onApplicationEnvironmentPreparedEvent(LoggingApplicationListener.java:246)
	at org.springframework.boot.context.logging.LoggingApplicationListener.onApplicationEvent(LoggingApplicationListener.java:223)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:172)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:165)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:139)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:127)
	at org.springframework.boot.context.event.EventPublishingRunListener.environmentPrepared(EventPublishingRunListener.java:76)
	at org.springframework.boot.SpringApplicationRunListeners.environmentPrepared(SpringApplicationRunListeners.java:53)
	at org.springframework.boot.SpringApplication.prepareEnvironment(SpringApplication.java:345)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:308)
	at org.springframework.boot.builder.SpringApplicationBuilder.run(SpringApplicationBuilder.java:140)
	at org.monarchinitiative.squirls.cli.cmd.SquirlsCommand.getContext(SquirlsCommand.java:174)
	at org.monarchinitiative.squirls.cli.cmd.annotate_vcf.AnnotateVcfCommand.call(AnnotateVcfCommand.java:255)
	at org.monarchinitiative.squirls.cli.cmd.annotate_vcf.AnnotateVcfCommand.call(AnnotateVcfCommand.java:120)
	at picocli.CommandLine.executeUserObject(CommandLine.java:1933)
	at picocli.CommandLine.access$1200(CommandLine.java:145)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2332)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2326)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2291)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2159)
	at picocli.CommandLine.execute(CommandLine.java:2058)
	at org.monarchinitiative.squirls.cli.Main.main(Main.java:124)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:87)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:51)
	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:52)

**Comment by ielis** [comment]
Hi @sitems 
the issue seems to be related to SQUIRLS not able to write a log file due to privileges mismatch.

Under the hood, SQUIRLS app uses Spring Framework to manage the configuration and Logback framework for logging. When you run the command, Logback fails to create a log file:

```
ERROR in ch.qos.logback.core.FileAppender[FILE] - openFile(squirls.log,false) call failed. java.io.FileNotFoundException: squirls.log (Permission denied)
```

I do not have a solution that is "guaranteed" to work at this time, but I think you should try to set an explicit path to the log file to your CLI invocation. [Spring documentation](https://docs.spring.io/spring-boot/reference/features/logging.html#features.logging.file-output) suggests using `logging.file.name` property to override the default log file location.  The property can be set via `-D` JVM option.

In practice, this should look like this:

```shell
LOG_PATH=path/to/squirls.log

docker run \
  --workdir /opt/squirls --network none --rm --mount type=bind,source="${BIOCACHE}"/squirls,target=/data,readonly --mount "type=bind,source=${PWD},target=/output" --mount "type=bind,source=${PWD}/family_decnorm_filt.vcf.bgz,target=/input/variants.vcf.bgz,readonly" \
urpin/squirls:2.0.0 \
java -Xmx1000g -Dlogging.file.name="${LOG_PATH}" -jar squirls-cli-2.0.0.jar \
annotate-vcf --output-format vcf,html --all-transcripts --transcript-source REFSEQ --compress --threads 1 --data-directory /data /input/variants.vcf.bgz /output/family_decnorm_filt_squirls
```

Note the `-Dlogging.file.name="${LOG_PATH}"` option and its location right after `java` to be used as JVM property.

I hope this helps you to solve the issue.

**Comment by sitems** [comment]
Thanks for your help. I tried that, but seems not to be working, so I leave it for now, since it's not such a big problem for me.

**Comment by ielis** [comment]
Sorry to hear that. I'll close the issue but please let me know if I can help with anything else.
